# encoding: ascii-8bit

# Copyright 2026 OpenC3, Inc.
# All Rights Reserved.
#
# Licensed for Evaluation and Educational Use
#
# This file may only be used commercially under the terms of a commercial license
# purchased from OpenC3, Inc.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

source ENV['RUBYGEMS_URL'] || "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 8.1.0'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.9.3', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 3.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data'

# NOTE: Since we're not using the Gemfile.lock we can't include development
# or test groups in the Gemfile or bundler tries to install them and fails

if ENV['OPENC3_DEVEL']
  gem 'openc3', :path => ENV['OPENC3_DEVEL']
elsif ENV['OPENC3_PATH']
  gem 'openc3', :path => ENV['OPENC3_PATH']
else
  gem 'openc3', '>= 7.0.0'
end

if ENV['OPENC3_ENTERPRISE_TAG']
  gem 'openc3-enterprise', '>= 7.0.0'
end
